// ==========================================================================
// Agni CRM — Mock Data for Marketing Operations & Client Services
// ==========================================================================

export const navItems = [
  { icon: "dashboard", label: "Dashboard" },
  { icon: "clients", label: "Client" },
  { icon: "overview", label: "Details" },
  { icon: "reports", label: "Services" },
];

export const branchOptions = ["East", "West", "South", "North"];

// Company Marketing Service Offerings Catalog
export const companyMarketingServices = [
  {
    id: "mkt-srv-1",
    name: "Performance Marketing & Multi-Channel Paid Ads",
    category: "Paid Media & Ads",
    description: "High-ROI Google Search & Display, Meta Ads (Facebook/Instagram), and LinkedIn B2B paid media management with automated conversion tracking and daily bid optimization.",
    tag: "High Conversion ROI",
    turnaround: "3-Day Launch",
    estimate: "₹25,000 / month",
    baseAmount: 25000,
    features: [
      "Targeted Google Search & PMax Campaigns",
      "Meta Ads Retargeting & Custom Audiences",
      "LinkedIn Sponsored Content & InMail Ads",
      "Daily ROAS & Conversion Tracking",
      "Custom Ad Creatives & Copywriting",
    ],
    scopeDetails: "Comprehensive media plan across Google, Meta, and LinkedIn with full GA4 tracking setup, custom UTM tracking, A/B ad creative testing, and weekly performance dashboards.",
    tone: "#4e7cff",
  },
  {
    id: "mkt-srv-2",
    name: "Search Engine Optimization (SEO) & Organic Growth",
    category: "SEO & Growth",
    description: "Enterprise technical SEO audits, high-intent keyword clustering, on-page optimization, quality backlink acquisition, and Google Core Web Vitals performance tuning.",
    tag: "Organic Page #1",
    turnaround: "Monthly Retainer",
    estimate: "₹20,000 / month",
    baseAmount: 20000,
    features: [
      "Full Site Technical SEO & Indexing Audit",
      "High-Intent Commercial Keyword Strategy",
      "High-Authority Backlink Outreach",
      "Core Web Vitals & Page Speed Tuning",
      "Google Search Console & GA4 Integration",
    ],
    scopeDetails: "Monthly organic search strategy including competitive gap analysis, schema markup implementation, editorial content calendar, and keyword ranking monitoring.",
    tone: "#10b981",
  },
  {
    id: "mkt-srv-3",
    name: "B2B Lead Generation & Automated Email Funnels",
    category: "Lead Generation & CRM",
    description: "Cold outreach automation, verified decision-maker prospect scraping, high-converting drip email sequences, and CRM pipeline automation.",
    tag: "Qualified MQL Pipeline",
    turnaround: "1-Week Setup",
    estimate: "₹35,000 / month",
    baseAmount: 35000,
    features: [
      "Verified B2B Prospect Data Sourcing",
      "Cold Email Drip Funnels & Warmup",
      "Automated CRM Lead Routing & Scoring",
      "A/B Tested Sales Outreach Copy",
      "Calendar Booking & Meeting Scheduling",
    ],
    scopeDetails: "End-to-end outbound pipeline setup with dedicated domain warm-up, multi-step email nurture flows, Apollo/LinkedIn data extraction, and CRM synchronization.",
    tone: "#9a74e9",
  },
  {
    id: "mkt-srv-4",
    name: "Social Media Management & Brand Community",
    category: "Social & Community",
    description: "Strategic social media calendar, graphic design, video reels/shorts production, community engagement, and thought-leadership positioning on LinkedIn & Instagram.",
    tag: "Brand Engagement",
    turnaround: "Ongoing Retainer",
    estimate: "₹18,000 / month",
    baseAmount: 18000,
    features: [
      "20 Monthly Branded Posts & Infographics",
      "Short-Form Video Production (Reels/Shorts)",
      "LinkedIn Thought Leadership Articles",
      "Community Comment & DM Moderation",
      "Monthly Engagement & Reach Analytics",
    ],
    scopeDetails: "Includes branded visual templates, monthly content planning, industry trend monitoring, influencer collaboration management, and hashtag optimization.",
    tone: "#f2aa38",
  },
  {
    id: "mkt-srv-5",
    name: "Brand Identity, UI/UX & Creative Graphic Design",
    category: "Design & Branding",
    description: "Corporate brand guidelines, logo modernization, high-converting landing page UI/UX wireframes, company pitch decks, and sales collateral design.",
    tag: "Premium Visual Identity",
    turnaround: "2 Weeks",
    estimate: "₹45,000 One-time",
    baseAmount: 45000,
    features: [
      "Complete Brand Style Guide & Typography",
      "Vector Logo & Modern Iconography Suite",
      "Conversion Landing Page Figma UI/UX",
      "Investor Pitch Deck & Brochure Design",
      "Print & Digital Marketing Assets",
    ],
    scopeDetails: "Full design sprint including stakeholder discovery, mood boards, vector asset delivery, typography scale, responsive Figma prototypes, and production-ready exports.",
    tone: "#f2938f",
  },
  {
    id: "mkt-srv-6",
    name: "Content Marketing & Enterprise PR Outreach",
    category: "Content & PR",
    description: "Data-backed industry whitepapers, SEO blog articles, press release distribution across national media outlets, and thought leadership positioning.",
    tag: "Authority & PR",
    turnaround: "2-3 Weeks",
    estimate: "₹30,000 / month",
    baseAmount: 30000,
    features: [
      "4 In-Depth Research Blog Articles / mo",
      "Press Release Drafting & Wire Distribution",
      "Industry Case Studies & Customer Stories",
      "National Tech & Business Media Coverage",
      "Media Placement & Backlink Verification",
    ],
    scopeDetails: "Full editorial curation, copywriting, technical proofreading, PR distribution across prominent news networks, and digital brand mention tracking.",
    tone: "#44bfb0",
  },
];

// Initial clients pitched by sales reps across branches where Service Request is "Marketing"
export const initialSalesPitchedMarketingClients = [
  {
    id: 201,
    name: "GreenEarth Organics",
    company: "GreenEarth Organics Pvt Ltd",
    contactPerson: "Ritika Sharma",
    email: "ritika@greenearthorganics.in",
    phone: "+91 98312 45678",
    address: "54 Salt Lake Sector 1, Kolkata",
    branch: "East",
    salesPerson: "Mia Ross",
    serviceType: "Marketing",
    serviceName: "Performance Marketing & Multi-Channel Paid Ads",
    amount: "50000",
    paymentMode: "Online",
    gstAmount: 9000,
    totalPayment: 59000,
    paymentReceived: "59000",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Urgent 24h",
    progress: 100,
    createdDate: "2026-07-18",
    notes: "Pitched by East branch sales rep for pan-India Meta & Google Ads D2C scale-up.",
  },
  {
    id: 202,
    name: "Kolkata Craft Guild",
    company: "Kolkata Craft Guild LLP",
    contactPerson: "Tanmoy Banerjee",
    email: "tanmoy@kolkatacraft.com",
    phone: "+91 91234 55443",
    address: "12 Park Street, Kolkata",
    branch: "East",
    salesPerson: "Alex Vance",
    serviceType: "Marketing",
    serviceName: "Social Media Management & Brand Community",
    amount: "36000",
    paymentMode: "Online",
    gstAmount: 6480,
    totalPayment: 42480,
    paymentReceived: "25000",
    paymentPending: 17480,
    stage: "In Progress",
    applicationStatus: "Manager Review",
    slaTier: "Standard Retainer",
    progress: 65,
    createdDate: "2026-08-04",
    notes: "Pitched for comprehensive Instagram Reels, festival campaigns, and influencer outreach.",
  },
  {
    id: 203,
    name: "Eastern Steel Infra",
    company: "Eastern Steel Infra Ltd",
    contactPerson: "Priya Mukherjee",
    email: "priya.m@easternsteel.in",
    phone: "+91 98301 99887",
    address: "77 Camac Street, Kolkata",
    branch: "East",
    salesPerson: "Kabir Sharma",
    serviceType: "Marketing",
    serviceName: "B2B Lead Generation & Automated Email Funnels",
    amount: "70000",
    paymentMode: "Online",
    gstAmount: 12600,
    totalPayment: 82600,
    paymentReceived: "45000",
    paymentPending: 37600,
    stage: "Agreement",
    applicationStatus: "Agreement",
    slaTier: "High Priority",
    progress: 80,
    createdDate: "2026-08-11",
    notes: "Pitched for decision-maker cold outreach to infrastructure builders and contractors.",
  },
  {
    id: 204,
    name: "BlueOcean FinTech",
    company: "BlueOcean FinTech Solutions",
    contactPerson: "Kunal Shah",
    email: "kunal@blueoceanfin.com",
    phone: "+91 99887 11223",
    address: "Bandra Kurla Complex, Mumbai",
    branch: "West",
    salesPerson: "Noah Kim",
    serviceType: "Marketing",
    serviceName: "Search Engine Optimization (SEO) & Organic Growth",
    amount: "40000",
    paymentMode: "Online",
    gstAmount: 7200,
    totalPayment: 47200,
    paymentReceived: "47200",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Standard Retainer",
    progress: 100,
    createdDate: "2026-06-25",
    notes: "Pitched by West branch rep for nationwide FinTech commercial keyword ranking.",
  },
  {
    id: 205,
    name: "Zenith Retail Hub",
    company: "Zenith Retailers India",
    contactPerson: "Arjun Reddy",
    email: "arjun@zenithretail.in",
    phone: "+91 98450 33221",
    address: "Indiranagar 100ft Road, Bangalore",
    branch: "South",
    salesPerson: "Emma Watson",
    serviceType: "Marketing",
    serviceName: "Brand Identity, UI/UX & Creative Graphic Design",
    amount: "45000",
    paymentMode: "Online",
    gstAmount: 8100,
    totalPayment: 53100,
    paymentReceived: "30000",
    paymentPending: 23100,
    stage: "In Progress",
    applicationStatus: "Review",
    slaTier: "High Priority",
    progress: 55,
    createdDate: "2026-07-29",
    notes: "Pitched by South branch for full brand rebranding, packaging, and digital style guide.",
  },
  {
    id: 206,
    name: "Capital Agro Tech",
    company: "Capital Agro Technologies Ltd",
    contactPerson: "Vikram Malhotra",
    email: "vikram@capitalagrotech.com",
    phone: "+91 98110 44556",
    address: "Connaught Place, New Delhi",
    branch: "North",
    salesPerson: "Liam Davis",
    serviceType: "Marketing",
    serviceName: "Content Marketing & Enterprise PR Outreach",
    amount: "60000",
    paymentMode: "Online",
    gstAmount: 10800,
    totalPayment: 70800,
    paymentReceived: "70800",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Urgent 24h",
    progress: 100,
    createdDate: "2026-08-01",
    notes: "Pitched by North branch for national agriculture media press coverage and whitepapers.",
  },
];

// Initial clients created directly from the Marketing Module
export const initialMarketingCreatedClients = [
  {
    id: 207,
    name: "Apex Healthcare AI",
    company: "Apex Healthcare AI Labs",
    contactPerson: "Dr. Sunita Ghosh",
    email: "sghosh@apexhealthai.com",
    phone: "+91 98305 66778",
    address: "Sector V, Salt Lake, Kolkata",
    branch: "East",
    salesPerson: "Marketing Lead",
    serviceType: "Marketing",
    serviceName: "Performance Marketing & Multi-Channel Paid Ads",
    amount: "50000",
    paymentMode: "Online",
    gstAmount: 9000,
    totalPayment: 59000,
    paymentReceived: "30000",
    paymentPending: 29000,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Urgent 24h",
    progress: 100,
    createdDate: "2026-08-16",
    notes: "Direct onboarding from Marketing Portal for multi-channel doctor and clinic acquisition ads.",
    isDirectCreated: true,
  },
  {
    id: 208,
    name: "Vedic Botanicals",
    company: "Vedic Botanicals India Pvt Ltd",
    contactPerson: "Alok Sengupta",
    email: "alok@vedicbotanicals.in",
    phone: "+91 97480 11234",
    address: "Rashbehari Avenue, Kolkata",
    branch: "East",
    salesPerson: "Marketing Lead",
    serviceType: "Marketing",
    serviceName: "Search Engine Optimization (SEO) & Organic Growth",
    amount: "20000",
    paymentMode: "Online",
    gstAmount: 3600,
    totalPayment: 23600,
    paymentReceived: "23600",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Standard Retainer",
    progress: 100,
    createdDate: "2026-08-17",
    notes: "Direct client onboarding for holistic skincare organic search visibility and local SEO.",
    isDirectCreated: true,
  },
];

// Marketing Activities
export const marketingActivities = [
  {
    id: "act-1",
    action: "New Client Onboarded",
    target: "Apex Healthcare AI",
    user: "Marketing Lead",
    time: "25m ago",
    status: "Live",
    type: "onboarding",
    branch: "East",
  },
  {
    id: "act-2",
    action: "Sales Pitch Request Received",
    target: "Eastern Steel Infra",
    user: "Kabir Sharma",
    time: "2h ago",
    status: "Review",
    type: "pitch",
    branch: "East",
  },
  {
    id: "act-3",
    action: "Campaign Media Plan Approved",
    target: "GreenEarth Organics",
    user: "Ritika Sharma",
    time: "5h ago",
    status: "Active",
    type: "media",
    branch: "East",
  },
  {
    id: "act-4",
    action: "PR Wire Coverage Published",
    target: "Capital Agro Tech",
    user: "Liam Davis",
    time: "1d ago",
    status: "Completed",
    type: "pr",
    branch: "North",
  },
];
