export const initialAdminRequests = [
  {
    id: "ARQ-301",
    clientAppId: "APP-WZ-2026-001",
    clientName: "Bright Retail",
    company: "Bright Retail Pvt Ltd",
    branch: "West Zone (Mumbai)",
    requestType: "Tracker Stage Rollback",
    currentStage: "Final",
    targetStage: "Application",
    recipient: "Branch Manager",
    reason: "Client requested minor clause modification in legal agreement before final commercial issuance. Need to roll back from 'Final' to 'Application' to re-upload revised annexure.",
    requestedChanges: [
      { field: "Milestone Stage", oldValue: "Final (100%)", newValue: "Application (80%)" },
      { field: "Active Status", oldValue: "Completed", newValue: "In Progress" },
    ],
    priority: "High",
    status: "Pending",
    createdAt: "2026-08-19",
    decisionDate: null,
    managerRemarks: null,
  },
  {
    id: "ARQ-302",
    clientAppId: "APP-WZ-2026-002",
    clientName: "Urban Foods",
    company: "Urban Foods Ltd",
    branch: "West Zone (Mumbai)",
    requestType: "Tracker Stage Rollback",
    currentStage: "Agreement",
    targetStage: "CRM Creation",
    recipient: "Branch Manager",
    reason: "GSTIN certificate uploaded during Agreement audit contained typographical error in entity PAN. Reverting to CRM Creation to update official identification.",
    requestedChanges: [
      { field: "Milestone Stage", oldValue: "Agreement (40%)", newValue: "CRM Creation (20%)" },
      { field: "GST Number", oldValue: "27PQRSX6789K1Z1", newValue: "27PQRSX6789K1Z2" },
    ],
    priority: "Urgent",
    status: "Approved",
    createdAt: "2026-08-15",
    decisionDate: "2026-08-16",
    managerRemarks: "Verified revised GST certificate with Maharashtra tax department. Rollback approved.",
  },
  {
    id: "ARQ-303",
    clientAppId: "APP-WZ-2026-004",
    clientName: "Nova Textiles",
    company: "Nova Textiles Co",
    branch: "West Zone (Mumbai)",
    requestType: "Tracker Stage Rollback",
    currentStage: "Agreement",
    targetStage: "CRM Creation",
    recipient: "Branch Manager",
    reason: "Client registration documents required correction in authorized signatory name. Rollback to CRM Creation approved.",
    requestedChanges: [
      { field: "Milestone Stage", oldValue: "Agreement (40%)", newValue: "CRM Creation (20%)" },
    ],
    priority: "Normal",
    status: "Approved",
    createdAt: "2026-08-10",
    decisionDate: "2026-08-11",
    managerRemarks: "Signatory documentation updated. Rollback granted.",
  },
  {
    id: "ARQ-304",
    clientAppId: "APP-WZ-2026-001",
    clientName: "Bright Retail",
    company: "Bright Retail Pvt Ltd",
    branch: "West Zone (Mumbai)",
    requestType: "Tracker Stage Rollback",
    currentStage: "Reports",
    targetStage: "CRM Creation",
    recipient: "Branch Manager",
    reason: "Requested full reset to CRM Creation due to incorrect client branch allocation.",
    requestedChanges: [
      { field: "Milestone Stage", oldValue: "Reports (60%)", newValue: "CRM Creation (20%)" },
    ],
    priority: "Normal",
    status: "Rejected",
    createdAt: "2026-08-05",
    decisionDate: "2026-08-06",
    managerRemarks: "Branch reallocation should be executed via inter-branch transfer instead of stage wipe. Rejected.",
  },
];
