export const initialManagerReceivedRequests = [
  {
    id: "MRQ-401",
    requesterName: "Eli Brooks",
    requesterRole: "Regional Sales Manager",
    requesterBranch: "South",
    targetName: "Bright Retail",
    targetType: "Client",
    requestType: "Edit Client",
    department: "Sales",
    reason: "Client requests update of corporate GSTIN and primary invoicing contact phone number.",
    requestedChanges: [
      { field: "GST Number", oldValue: "27AABBCC1234Z1", newValue: "27AABBCC1234Z2" },
      { field: "Contact Phone", oldValue: "+91 98765 32100", newValue: "+91 98765 32199" },
    ],
    status: "Pending",
    createdAt: "2026-08-18",
    priority: "High",
    decisionDate: null,
    decisionRemarks: null,
  },
  {
    id: "MRQ-402",
    requesterName: "Daniel Cruz",
    requesterRole: "Regional Sales Manager",
    requesterBranch: "South",
    targetName: "Alpha Logistics",
    targetType: "Client",
    requestType: "Delete Client",
    department: "Sales",
    reason: "Duplicate profile created in CRM due to CRM account migration error.",
    requestedChanges: [],
    status: "Pending",
    createdAt: "2026-08-19",
    priority: "Normal",
    decisionDate: null,
    decisionRemarks: null,
  },
  {
    id: "MRQ-403",
    requesterName: "Eli Brooks",
    requesterRole: "Regional Sales Manager",
    requesterBranch: "South",
    targetName: "Urban Foods Ltd",
    targetType: "Client",
    requestType: "Edit Client",
    department: "Sales",
    reason: "Client entity upgraded to corporate enterprise scheme tier.",
    requestedChanges: [
      { field: "Scheme", oldValue: "Retail Scale-Up Program", newValue: "Enterprise Growth Scheme" },
      { field: "Billing Amount", oldValue: "₹45,000", newValue: "₹85,000" },
    ],
    status: "Approved",
    createdAt: "2026-08-12",
    priority: "High",
    decisionDate: "2026-08-14",
    decisionRemarks: "Verified scheme upgrade documentation. Approved.",
  },
  {
    id: "MRQ-404",
    requesterName: "Daniel Cruz",
    requesterRole: "Regional Sales Manager",
    requesterBranch: "South",
    targetName: "Apex Retail",
    targetType: "Client",
    requestType: "Delete Client",
    department: "Sales",
    reason: "Client decided to terminate contract early before onboarding completion.",
    requestedChanges: [],
    status: "Rejected",
    createdAt: "2026-08-05",
    priority: "Normal",
    decisionDate: "2026-08-07",
    decisionRemarks: "Client retention team is currently negotiating renewal. Deletion rejected.",
  },
];

export const initialBranchSentRequests = [
  {
    id: "BMR-801",
    department: "Manager",
    targetId: 1,
    targetName: "Eli Brooks",
    targetRole: "Regional Sales Manager",
    targetBranch: "South",
    requestType: "Edit Profile",
    recipient: "Owner",
    reason: "Promote Eli Brooks to Senior Regional Manager and update quarterly quota targets.",
    requestedChanges: [
      { field: "Designation", oldValue: "Regional Sales Manager", newValue: "Senior Regional Sales Manager" },
      { field: "Assigned Quota", oldValue: "₹120k", newValue: "₹180k" },
      { field: "Territory Region", oldValue: "South Zone", newValue: "South & Coastal Zone" },
    ],
    status: "Pending",
    createdAt: "2026-08-17",
    priority: "High",
    ownerRemarks: null,
    decisionDate: null,
  },
  {
    id: "BMR-802",
    department: "Admin",
    targetId: 1,
    targetName: "Sara Kim",
    targetRole: "Branch Administrator",
    targetBranch: "North",
    requestType: "Transfer Staff",
    recipient: "Owner",
    destinationBranch: "East",
    reason: "Staff relocation request to East Regional Branch to manage expanding customer onboarding volume.",
    requestedChanges: [
      { field: "Assigned Branch", oldValue: "North Branch", newValue: "East Branch" },
      { field: "Reporting Manager", oldValue: "Ariana Lee", newValue: "East Branch Lead" },
    ],
    status: "Pending",
    createdAt: "2026-08-18",
    priority: "Normal",
    ownerRemarks: null,
    decisionDate: null,
  },
  {
    id: "BMR-803",
    department: "IT",
    targetId: 2,
    targetName: "Janet Paul",
    targetRole: "Systems Administrator",
    targetBranch: "West",
    requestType: "Delete Staff",
    recipient: "Owner",
    reason: "Employee resignation submitted. Requesting account offboarding and access revoke.",
    requestedChanges: [],
    status: "Approved",
    createdAt: "2026-08-01",
    priority: "High",
    ownerRemarks: "Approved by Owner. Access credentials scheduled for deactivation.",
    decisionDate: "2026-08-03",
  },
  {
    id: "BMR-804",
    department: "Marketing",
    targetId: 1,
    targetName: "Daniel Cruz",
    targetRole: "Marketing Specialist",
    targetBranch: "South",
    requestType: "Edit Profile",
    recipient: "Owner",
    reason: "Update marketing compensation tier and assign enterprise campaign lead role.",
    requestedChanges: [
      { field: "Designation", oldValue: "Marketing Specialist", newValue: "Lead Marketing Strategist" },
      { field: "Email", oldValue: "daniel@agni.com", newValue: "daniel.cruz@agni.com" },
    ],
    status: "Approved",
    createdAt: "2026-07-25",
    priority: "Normal",
    ownerRemarks: "Approved. Role permissions updated across CRM.",
    decisionDate: "2026-07-28",
  },
];
