import { mockEligibleSchemes } from "./mockEligibleSchemes";

export const GST_RATE = 0.18; // 18% GST applied only when payment mode is Online

export const serviceTypeSchemes = {
  Certificate: [
    "PMEGP",
    "PM MUDRA",
    "CGTMSE",
    "NAIFF",
    "NLM",
    "AHIDF",
    "CGSS",
    "Financial Assistant SC/ST",
    "Private Funding",
    "Equity Based Funding",
    "DIV Funding",
    "NGO Elevation",
    "NGO Development",
    "CSR",
    "Spark Grant",
    "Growth Grant",
    "MSME Design",
    "Mudra Export Certification",
    "MSME ZED Certification",
    "ISO Certification Suite",
    "Corporate Health Shield Annual",
    "Startup India Seed Scheme",
  ],
  IT: [
    "Enterprise Web Portal & CRM Maintenance",
    "Cybersecurity Vulnerability & Pen-Test Audit",
    "Cloud Infrastructure Setup & AWS/Azure Migration",
    "Enterprise VoIP, VPN & Remote Network Architecture",
    "Custom API Integration & Microservices Gateway",
    "IT Hardware Fleet & Device Management (MDM)",
    "Enterprise CRM Setup",
    "Supply Chain Analytics Platform",
  ],
  Marketing: [
    "Performance Marketing & Multi-Channel Paid Ads",
    "Search Engine Optimization (SEO) & Organic Growth",
    "B2B Lead Generation & Automated Email Funnels",
    "Social Media Management & Brand Community",
    "Brand Identity, UI/UX & Creative Graphic Design",
    "Content Marketing & Enterprise PR Outreach",
    "Website & Brand Growth Suite",
  ],
};

export const schemeOptions = mockEligibleSchemes.map((scheme) => scheme.schemeName);

export const navItems = [
  { icon: "dashboard", label: "Dashboard" },
  { icon: "clients", label: "Clients" },
  { icon: "overview", label: "Requests" },
  { icon: "invoice", label: "Invoices" },
  { icon: "wallet", label: "Payment" },
  { icon: "reports", label: "Details" },
];

export const salesLeads = [
  { id: 1, client: "Bright Retail", contact: "Anil Kumar", status: "Proposal", value: "₹58k", owner: "Mia Ross" },
  { id: 2, client: "Urban Foods", contact: "Riya Sharma", status: "Negotiation", value: "₹46k", owner: "Rohan Varma" },
  { id: 3, client: "Nova Textiles", contact: "Sanjay Patel", status: "Qualified", value: "₹34k", owner: "Noah Kim" },
  { id: 4, client: "Peak Logistics", contact: "Rakesh Mehra", status: "Demo", value: "₹72k", owner: "Tara Singh" },
];

export const initialSalesClients = [
  {
    id: 1,
    name: "Bright Retail",
    contactPerson: "Anil Kumar",
    company: "Bright Retail Pvt Ltd",
    email: "hello@brightretail.com",
    phone: "+91 98765 32100",
    address: "101 MG Road, Fort, Mumbai",
    stage: "Active",
    owner: "Mia Ross",
    scheme: schemeOptions[0] || "Enterprise Growth Scheme",
    amount: "50000",
    paymentMode: "Online",
    gstAmount: 9000,
    totalPayment: 59000,
    paymentReceived: "59000",
    paymentPending: 0,
    notes: "Key retail client onboarded for the annual growth scheme. High customer satisfaction.",
    documentDetails: [
      { label: "PAN Number", value: "ABCDE1234F", available: "Yes" },
      { label: "Aadhar Number", value: "1234 5678 9012", available: "Yes" },
      { label: "GST Number", value: "27ABCDE1234F1Z5", available: "Yes" },
      { label: "KYC Documents", value: "Submitted", available: "Yes" },
    ],
  },
  {
    id: 2,
    name: "Urban Foods",
    contactPerson: "Riya Sharma",
    company: "Urban Foods Ltd",
    email: "sales@urbanfoods.com",
    phone: "+91 91234 55678",
    address: "22 Brigade Road, Indiranagar, Bengaluru",
    stage: "Onboarding",
    owner: "Mia Ross",
    scheme: schemeOptions[1] || "Retail Scale-Up Program",
    amount: "45000",
    paymentMode: "Online",
    gstAmount: 8100,
    totalPayment: 53100,
    paymentReceived: "30000",
    paymentPending: 23100,
    notes: "Initial installment processed. KYC verification documents under review.",
    documentDetails: [
      { label: "PAN Number", value: "PQRSX6789K", available: "Yes" },
      { label: "Aadhar Number", value: "2345 6789 0123", available: "Yes" },
      { label: "GST Number", value: "27PQRSX6789K1Z1", available: "Yes" },
      { label: "KYC Documents", value: "Pending", available: "No" },
    ],
  },
  {
    id: 3,
    name: "Nova Textiles",
    contactPerson: "Sanjay Patel",
    company: "Nova Textiles Co",
    email: "contact@novatextiles.com",
    phone: "+91 99876 44556",
    address: "17 Industrial Park, Ring Road, Surat",
    stage: "Renewal",
    owner: "Rohan Varma",
    scheme: schemeOptions[2] || "Textile Machinery Subsidy",
    amount: "75000",
    paymentMode: "Offline",
    gstAmount: 0,
    totalPayment: 75000,
    paymentReceived: "75000",
    paymentPending: 0,
    notes: "Renewal completed via direct wire transfer. Eligible for upcoming state incentive subsidies.",
    documentDetails: [
      { label: "PAN Number", value: "LMNOP4321D", available: "Yes" },
      { label: "Aadhar Number", value: "3456 7890 1234", available: "Yes" },
      { label: "GST Number", value: "27LMNOP4321D1Z3", available: "Yes" },
      { label: "KYC Documents", value: "Submitted", available: "Yes" },
    ],
  },
  {
    id: 4,
    name: "Peak Logistics",
    contactPerson: "Rakesh Mehra",
    company: "Peak Logistics Pvt Ltd",
    email: "contact@peaklogistics.com",
    phone: "+91 90123 45678",
    address: "38 Freight Lane, GIDC, Ahmedabad",
    stage: "Active",
    owner: "Tara Singh",
    scheme: schemeOptions[3] || "Fleet Modernization Grant",
    amount: "120000",
    paymentMode: "Online",
    gstAmount: 21600,
    totalPayment: 141600,
    paymentReceived: "70800",
    paymentPending: 70800,
    notes: "First milestone payment received. Aadhar update requested for final sign-off.",
    documentDetails: [
      { label: "PAN Number", value: "RSTUV9876P", available: "Yes" },
      { label: "Aadhar Number", value: "4567 8901 2345", available: "No" },
      { label: "GST Number", value: "27RSTUV9876P1Z2", available: "Yes" },
      { label: "KYC Documents", value: "Pending", available: "No" },
    ],
  },
];

export const notifications = [
  { title: "New lead assigned", detail: "4 leads were assigned to your queue.", issuer: "CRM", tone: "#9a74e9" },
  { title: "Deal updated", detail: "Urban Foods moved to Negotiation.", issuer: "Sales Ops", tone: "#44bfb0" },
  { title: "Quota alert", detail: "You are 18% ahead of pace.", issuer: "System", tone: "#f2aa38" },
];

export const requestActivities = [
  { title: "Request approved", detail: "Client update request approved by management.", time: "2m ago", tone: "#44bfb0" },
  { title: "Request rejected", detail: "Delete request rejected for Nova Textiles.", time: "1h ago", tone: "#f2aa38" },
  { title: "New request", detail: "A new approval request is ready for review.", time: "3h ago", tone: "#9a74e3" },
];

export const initialNewClientState = {
  name: "",
  contactPerson: "",
  company: "",
  email: "",
  phone: "",
  address: "",
  serviceType: "Certificate",
  stage: "Active",
  scheme: schemeOptions[0] || "Standard Scheme",
  amount: "",
  paymentMode: "Online",
  gstAmount: 0,
  totalPayment: 0,
  paymentReceived: "",
  paymentPending: 0,
  panNumber: "",
  aadharNumber: "",
  gstNumber: "",
  kycStatus: "Submitted",
  notes: "",
};
