import { getProcessTypeForScheme } from "../utils/schemeTracker";

export const mockEligibleSchemes = [
  // Application Only
  {
    id: 1,
    schemeName: "PMEGP",
    description: "Prime Minister Employment Generation Programme for credit-linked subsidy on new micro-enterprises.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-08-01",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 2,
    schemeName: "PM MUDRA",
    description: "Collateral-free institutional credit financing support up to ₹10 Lakhs for micro and small units.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-07-28",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 3,
    schemeName: "CGTMSE",
    description: "Credit Guarantee Fund Trust for Micro and Small Enterprises collateral-free loan coverage.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-07-24",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 4,
    schemeName: "NAIFF",
    description: "National Agriculture Infrastructure Financing Facility for farm-gate harvest management.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-07-20",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 5,
    schemeName: "NLM",
    description: "National Livestock Mission subsidy assistance for animal husbandry and livestock farming.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-07-18",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 6,
    schemeName: "AHIDF",
    description: "Animal Husbandry Infrastructure Development Fund for dairy, meat processing, and animal feed plants.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-07-15",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 7,
    schemeName: "CGSS",
    description: "Credit Guarantee Scheme for Startups to provide credit guarantee coverage to DPIIT-recognized startups.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-07-12",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 8,
    schemeName: "Financial Assistant SC/ST",
    description: "Dedicated capital subsidy and financial assistance framework for SC/ST registered entrepreneurs.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-07-10",
    updatedBy: "Eligibility Engine",
  },

  // Interview Only
  {
    id: 9,
    schemeName: "Private Funding",
    description: "Angel investor and syndicate venture capital funding accessed via evaluation board interview.",
    eligible: true,
    visibleToClient: true,
    processType: "interview",
    lastUpdated: "2026-07-08",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 10,
    schemeName: "Equity Based Funding",
    description: "Growth capital equity infusion for high-potential scaling businesses via investor panel pitch.",
    eligible: true,
    visibleToClient: true,
    processType: "interview",
    lastUpdated: "2026-07-05",
    updatedBy: "Eligibility Engine",
  },

  // Application + Interview
  {
    id: 11,
    schemeName: "DIV Funding",
    description: "Development Innovation Ventures global grant funding requiring full dossier intake and board presentation.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-07-02",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 12,
    schemeName: "NGO Elevation",
    description: "Institutional grant enablement and elevation program for non-profit and social enterprise initiatives.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-06-28",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 13,
    schemeName: "NGO Development",
    description: "Capacity building and donor-matching framework for non-governmental development organizations.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-06-25",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 14,
    schemeName: "CSR",
    description: "Corporate Social Responsibility statutory fund allocation matching for high-impact social projects.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-06-20",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 15,
    schemeName: "Spark Grant",
    description: "Seed stage innovation spark grant supporting pilot proof-of-concept and prototyping.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-06-15",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 16,
    schemeName: "Growth Grant",
    description: "Mid-scale expansion grant for proven models scaling regional and national market penetration.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-06-10",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 17,
    schemeName: "MSME Design",
    description: "Ministry design clinic and product enhancement grant for modernizing manufacturing lines.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-06-05",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 18,
    schemeName: "Seed Funding",
    description: "Early-stage seed capital assistance for prototyping, proof-of-concept, and commercial validation.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-06-01",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 19,
    schemeName: "DIV",
    description: "Development Innovation Ventures grant program supporting breakthrough solutions for global development.",
    eligible: true,
    visibleToClient: true,
    processType: "application_interview",
    lastUpdated: "2026-05-28",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 20,
    schemeName: "Animal Husbandry",
    description: "Comprehensive financial support and infrastructure funding for livestock, dairy, and feed processing.",
    eligible: true,
    visibleToClient: true,
    processType: "application",
    lastUpdated: "2026-05-25",
    updatedBy: "Eligibility Engine",
  },
];
