export const navItems = [
  { icon: "dashboard", label: "Dashboard" },
  { icon: "team", label: "Client" },
  { icon: "overview", label: "Details" },
  { icon: "reports", label: "Services" },
];

export const branchOptions = [
  { label: "East Branch", value: "East" },
  { label: "West Branch", value: "West" },
  { label: "South Branch", value: "South" },
  { label: "North Branch", value: "North" },
];

export const companyITServices = [
  {
    id: "it-srv-1",
    name: "Enterprise Web Portal & CRM Maintenance",
    category: "Infrastructure & Web",
    description: "24/7 technical monitoring, database backup management, vulnerability patching, and SLA incident response for corporate web portals and custom CRM platforms.",
    tag: "24/7 SLA Guarantee",
    turnaround: "Instant Onboarding",
    estimate: "₹18,000 / month",
    baseAmount: 18000,
    features: [
      "99.99% Guaranteed SLA Uptime",
      "Automated Hourly Database Backups",
      "Dedicated DevOps Lead Assigned",
      "Zero-Downtime Hotfix Deployments",
      "Real-time Telemetry & Health Monitoring",
    ],
    scopeDetails: "Includes complete application layer monitoring, SSL renewals, monthly security audit, load balancer tuning, and priority support.",
    tone: "#4e7cff",
  },
  {
    id: "it-srv-2",
    name: "Cybersecurity Vulnerability & Pen-Test Audit",
    category: "Security & Compliance",
    description: "Rigorous penetration testing, cloud firewall inspection, source code security review, and threat surface auditing for enterprise IT infrastructure.",
    tag: "Security Penetration",
    turnaround: "48-Hour Audit",
    estimate: "₹45,000 / Audit",
    baseAmount: 45000,
    features: [
      "OWASP Top 10 Vulnerability Scan",
      "Cloud IAM & Firewall Hardening",
      "Comprehensive Executive Risk Report",
      "Step-by-step Remediation Roadmap",
      "ISO 27001 & SOC-2 Compliance Audit",
    ],
    scopeDetails: "Full white-box & black-box assessment of web apps, API endpoints, internal networks, and identity access management policies.",
    tone: "#9a74e9",
  },
  {
    id: "it-srv-3",
    name: "Cloud Infrastructure Setup & AWS/Azure Migration",
    category: "Cloud & DevOps",
    description: "End-to-end cloud architecture design, Kubernetes container orchestration, VPC networking, auto-scaling clusters, and multi-region disaster recovery.",
    tag: "High Availability",
    turnaround: "2-3 Weeks",
    estimate: "₹65,000 One-time",
    baseAmount: 65000,
    features: [
      "Terraform Infrastructure as Code (IaC)",
      "Multi-Region Auto-Failover Setup",
      "CI/CD Automated Deployment Pipelines",
      "Cloud Cost Optimization (up to 35% savings)",
      "Docker & Kubernetes Cluster Hardening",
    ],
    scopeDetails: "Seamless migration of databases, workloads, and DNS without application downtime, paired with complete architecture diagrams.",
    tone: "#44bfb0",
  },
  {
    id: "it-srv-5",
    name: "Enterprise VoIP, VPN & Remote Network Architecture",
    category: "Networking & Remote Access",
    description: "Secure corporate zero-trust network access (ZTNA), branch-to-branch VPN mesh, Cisco Meraki firewall administration, and SIP/VoIP cloud PBX telephony.",
    tag: "Zero-Trust Mesh",
    turnaround: "Same-Day Deployment",
    estimate: "₹22,000 / Branch",
    baseAmount: 22000,
    features: [
      "Hardware Token & TOTP 2FA Verification",
      "WireGuard & IPsec Encrypted Tunnels",
      "Branch Office QoS Traffic Prioritization",
      "SIP Softphone Provisioning & Mapping",
      "24/7 Rogue Device Intrusion Detection",
    ],
    scopeDetails: "Configures remote workforce gateways, mapped desktop extensions, failover broadband lines, and network policy enforcement.",
    tone: "#f2aa38",
  },
  {
    id: "it-srv-6",
    name: "Custom API Integration & Microservices Gateway",
    category: "Software Engineering",
    description: "Secure RESTful & GraphQL microservice gateways, payment gateway webhooks, SMS/WhatsApp communications API, and ERP interoperability pipelines.",
    tag: "Custom Integration",
    turnaround: "1-2 Weeks",
    estimate: "₹50,000 / Integration",
    baseAmount: 50000,
    features: [
      "Enterprise OAuth2 & JWT Token Auth",
      "Rate Limiting & DDoS Shielding",
      "Automated Swagger/OpenAPI Specs",
      "Asynchronous Webhook Event Queues",
      "SDK Integration for Web & Mobile",
    ],
    scopeDetails: "Builds high-throughput middleware adapters connecting ERP, payment processors, GST gateways, and CRM notification workers.",
    tone: "#f2938f",
  },
  {
    id: "it-srv-7",
    name: "IT Hardware Fleet & Device Management (MDM)",
    category: "End-User Computing",
    description: "Centralized Mobile Device Management (MDM), asset lifecycle tracking, remote wipe capabilities, OS image provisioning, and hardware warranty monitoring.",
    tag: "Device Fleet Control",
    turnaround: "Instant Provisioning",
    estimate: "₹850 / Device / mo",
    baseAmount: 25000,
    features: [
      "Apple Business Manager & Windows Autopilot",
      "Remote Lock, Wipe & BitLocker Encryption",
      "Asset Barcode Tagging & Inventory Sync",
      "Quarterly Hardware Health Audits",
      "Automated OS Patch Compliance",
    ],
    scopeDetails: "Complete MDM agent rollout, endpoint protection policy compliance, and automated workstation onboarding packages.",
    tone: "#6366f1",
  },
];

// Initial clients pitched by sales persons across branches where Service Request is "IT"
export const initialSalesPitchedITClients = [
  {
    id: 101,
    name: "Apex Logistics Hub",
    company: "Apex Logistics Hub Pvt Ltd",
    contactPerson: "Rohan Varma",
    email: "rohan@apexlogistics.in",
    phone: "+91 98765 44321",
    address: "Plot 14, Salt Lake Sector V, Kolkata",
    branch: "East",
    salesPerson: "Mia Ross",
    serviceType: "IT",
    serviceName: "Enterprise Web Portal & CRM Maintenance",
    amount: "75000",
    paymentMode: "Online",
    gstAmount: 13500,
    totalPayment: 88500,
    paymentReceived: "88500",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Urgent 24h",
    progress: 100,
    createdDate: "2026-07-15",
    notes: "Pitched by East branch sales team for full custom portal and 24/7 SLA monitoring.",
  },
  {
    id: 102,
    name: "Bengal BioPharma",
    company: "Bengal BioPharma Labs",
    contactPerson: "Dr. Arindam Sen",
    email: "sen@bengalbiopharma.com",
    phone: "+91 91234 88776",
    address: "24 Park Street, Kolkata",
    branch: "East",
    salesPerson: "Alex Vance",
    serviceType: "IT",
    serviceName: "Cybersecurity Vulnerability & Pen-Test Audit",
    amount: "45000",
    paymentMode: "Online",
    gstAmount: 8100,
    totalPayment: 53100,
    paymentReceived: "30000",
    paymentPending: 23100,
    stage: "In Progress",
    applicationStatus: "Manager Review",
    slaTier: "High Priority",
    progress: 60,
    createdDate: "2026-08-02",
    notes: "Mandatory compliance security audit required before international FDA portal launch.",
  },
  {
    id: 103,
    name: "Eastern Express Courier",
    company: "Eastern Express Logistics Ltd",
    contactPerson: "Debashis Roy",
    email: "droy@easternexpress.com",
    phone: "+91 98300 12345",
    address: "88 Camac Street, Kolkata",
    branch: "East",
    salesPerson: "Kabir Sharma",
    serviceType: "IT",
    serviceName: "Enterprise VoIP, VPN & Remote Network Architecture",
    amount: "66000",
    paymentMode: "Online",
    gstAmount: 11880,
    totalPayment: 77880,
    paymentReceived: "40000",
    paymentPending: 37880,
    stage: "Agreement",
    applicationStatus: "Agreement",
    slaTier: "Standard Retainer",
    progress: 80,
    createdDate: "2026-08-10",
    notes: "Pitched for multi-office VoIP telephony and WireGuard encrypted VPN network.",
  },
  {
    id: 104,
    name: "Nova Textiles Co",
    company: "Nova Textiles Co Pvt Ltd",
    contactPerson: "Sanjay Patel",
    email: "contact@novatextiles.com",
    phone: "+91 99876 44556",
    address: "17 Industrial Park, Surat",
    branch: "West",
    salesPerson: "Noah Kim",
    serviceType: "IT",
    serviceName: "Cloud Infrastructure Setup & AWS/Azure Migration",
    amount: "65000",
    paymentMode: "Online",
    gstAmount: 11700,
    totalPayment: 76700,
    paymentReceived: "76700",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Urgent 24h",
    progress: 100,
    createdDate: "2026-06-20",
    notes: "Cloud architecture setup, VPC networking, and multi-region disaster recovery deployment.",
  },
  {
    id: 105,
    name: "Summit Health Tech",
    company: "Summit Co.",
    contactPerson: "Vikram Iyer",
    email: "hello@summitco.com",
    phone: "+91 91234 56789",
    address: "88 Residency Road, Bengaluru",
    branch: "South",
    salesPerson: "Rohan Varma",
    serviceType: "IT",
    serviceName: "Enterprise Web Portal & CRM Maintenance",
    amount: "85000",
    paymentMode: "Online",
    gstAmount: 15300,
    totalPayment: 100300,
    paymentReceived: "60000",
    paymentPending: 40300,
    stage: "In Progress",
    applicationStatus: "Doc Audit",
    slaTier: "High Priority",
    progress: 40,
    createdDate: "2026-07-28",
    notes: "South branch enterprise client requiring custom integration and maintenance.",
  },
  {
    id: 106,
    name: "Capital Cloud Systems",
    company: "Capital Cloud Solutions",
    contactPerson: "Meenakshi Sundaram",
    email: "meenakshi@capitalcloud.in",
    phone: "+91 98111 44556",
    address: "12 Connaught Place, New Delhi",
    branch: "North",
    salesPerson: "Tara Singh",
    serviceType: "IT",
    serviceName: "Cloud Infrastructure Setup & AWS/Azure Migration",
    amount: "95000",
    paymentMode: "Online",
    gstAmount: 17100,
    totalPayment: 112100,
    paymentReceived: "112100",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Enterprise Dedicated",
    progress: 100,
    createdDate: "2026-05-18",
    notes: "Full AWS migration with Kubernetes and multi-region failover.",
  },
];

export const initialITCreatedClients = [
  {
    id: 201,
    name: "Horizon FinTech Labs",
    company: "Horizon FinTech Pvt Ltd",
    contactPerson: "Kunal Bansal",
    email: "kunal@horizonfin.io",
    phone: "+91 98450 99881",
    address: "Tower 3, IT Park, Kolkata",
    branch: "East",
    salesPerson: "IT Administrator",
    serviceType: "IT",
    serviceName: "Custom API Integration & Microservices Gateway",
    amount: "50000",
    paymentMode: "Online",
    gstAmount: 9000,
    totalPayment: 59000,
    paymentReceived: "59000",
    paymentPending: 0,
    stage: "Active",
    applicationStatus: "Final Approval",
    slaTier: "Urgent 24h",
    progress: 100,
    createdDate: "2026-08-16",
    notes: "Direct onboarding from IT dashboard. Payment gateway webhooks & OAuth2 setup.",
  },
  {
    id: 202,
    name: "Sona Retail Dynamics",
    company: "Sona Retail Dynamics LLP",
    contactPerson: "Priya Mukherjee",
    email: "priya@sonaretail.com",
    phone: "+91 97480 33445",
    address: "52 Gariahat Road, Kolkata",
    branch: "East",
    salesPerson: "IT Administrator",
    serviceType: "IT",
    serviceName: "IT Hardware Fleet & Device Management (MDM)",
    amount: "34000",
    paymentMode: "Online",
    gstAmount: 6120,
    totalPayment: 40120,
    paymentReceived: "25000",
    paymentPending: 15120,
    stage: "In Progress",
    applicationStatus: "Agreement",
    slaTier: "Standard Retainer",
    progress: 75,
    createdDate: "2026-08-17",
    notes: "MDM rollout across 40 POS tablets and store laptops.",
  },
];

export const itActivities = [
  {
    title: "New IT Client Onboarded: Horizon FinTech",
    detail: "Custom API Integration scope verified and production gateway active.",
    time: "45 mins ago",
    tone: "#10b981",
  },
  {
    title: "Sales Pitch Recorded: Apex Logistics Hub",
    detail: "East branch lead Mia Ross pitched 24/7 Web Portal & CRM Maintenance.",
    time: "2 hrs ago",
    tone: "#4e7cff",
  },
  {
    title: "Security Audit Requested: Bengal BioPharma",
    detail: "Pen-test schedule finalized for August 20th with full compliance report.",
    time: "4 hrs ago",
    tone: "#9a74e9",
  },
  {
    title: "Service Catalog Updated",
    detail: "MDM Device Fleet Management added with instant Apple/Windows autopilot.",
    time: "Yesterday",
    tone: "#f2aa38",
  },
];
