export const mockRequests = [
  {
    id: "RQ-1001",
    clientId: 1,
    clientName: "Bright Retail",
    managerId: 1,
    managerName: "Mia Ross",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Company Name", oldValue: "Bright Retail Pvt Ltd", newValue: "Bright Retail Enterprises" },
      { field: "Phone Number", oldValue: "+91 98765 32100", newValue: "+91 98765 32111" },
    ],
    reason: "Update company branding and phone number after branch expansion.",
    status: "Pending",
    createdAt: "2026-06-12",
    decisionDate: null,
    managerRemarks: null,
  },
  {
    id: "RQ-1002",
    clientId: 2,
    clientName: "Urban Foods",
    managerId: 2,
    managerName: "Rohan Varma",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Client account is no longer active and should be removed once approved.",
    status: "Pending",
    createdAt: "2026-07-02",
    decisionDate: null,
    managerRemarks: null,
  },
  {
    id: "RQ-1003",
    clientId: 3,
    clientName: "Nova Textiles",
    managerId: 1,
    managerName: "Mia Ross",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "GST Number", oldValue: "27LMNOP4321D1Z3", newValue: "27LMNOP4321D1Z8" },
      { field: "Address", oldValue: "17 Industrial Park, Surat", newValue: "17 Industrial Park, Surat - Phase 2" },
    ],
    reason: "Correct GST number and include updated warehouse address.",
    status: "Approved",
    createdAt: "2025-11-21",
    decisionDate: "2025-11-29",
    managerRemarks: "Approved after verifying updated GST documentation.",
  },
  {
    id: "RQ-1004",
    clientId: 4,
    clientName: "Peak Logistics",
    managerId: 3,
    managerName: "Tara Singh",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "The client account is duplicated and should be removed once manager approves.",
    status: "Rejected",
    createdAt: "2025-09-15",
    decisionDate: "2025-09-18",
    managerRemarks: "Deletion rejected until active service contract is closed.",
  },
  {
    id: "RQ-1005",
    clientId: 5,
    clientName: "Crest Pharma",
    managerId: 2,
    managerName: "Rohan Varma",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Contact Person", oldValue: "Deepa Joshi", newValue: "Deepa Joshi-Singh" },
      { field: "Email", oldValue: "support@crestpharma.com", newValue: "hello@crestpharma.com" },
    ],
    reason: "Update contact details after representative change.",
    status: "Cancelled",
    createdAt: "2025-08-03",
    decisionDate: "2025-08-03",
    managerRemarks: "Request cancelled by the salesperson before review.",
  },
  {
    id: "RQ-1006",
    clientId: 6,
    clientName: "Riverstone Builders",
    managerId: 3,
    managerName: "Tara Singh",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Client was moved to a competitor and should be deleted after manager confirmation.",
    status: "Approved",
    createdAt: "2024-12-18",
    decisionDate: "2025-01-04",
    managerRemarks: "Deletion approved after internal review.",
  },
  {
    id: "RQ-1007",
    clientId: 1,
    clientName: "Bright Retail",
    managerId: 1,
    managerName: "Mia Ross",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Contact Person", oldValue: "Anil Kumar", newValue: "Anil Kumar (Senior)" },
    ],
    reason: "Update contact title after promotion.",
    status: "Approved",
    createdAt: "2024-02-11",
    decisionDate: "2024-02-18",
    managerRemarks: "Approved with no follow-up needed.",
  },
  {
    id: "RQ-1008",
    clientId: 3,
    clientName: "Nova Textiles",
    managerId: 1,
    managerName: "Mia Ross",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Requested deletion after contract expiration.",
    status: "Rejected",
    createdAt: "2024-05-30",
    decisionDate: "2024-06-03",
    managerRemarks: "Rejected until all invoices are settled.",
  },
  {
    id: "RQ-1009",
    clientId: 2,
    clientName: "Urban Foods",
    managerId: 2,
    managerName: "Rohan Varma",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Company Name", oldValue: "Urban Foods Ltd", newValue: "Urban Foods Private Limited" },
      { field: "Address", oldValue: "22 Brigade Road, Bengaluru", newValue: "22 Brigade Road, Bengaluru - 2nd Floor" },
    ],
    reason: "Update company legal name and address.",
    status: "Pending",
    createdAt: "2026-03-08",
    decisionDate: null,
    managerRemarks: null,
  },
  {
    id: "RQ-1010",
    clientId: 5,
    clientName: "Crest Pharma",
    managerId: 2,
    managerName: "Rohan Varma",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Client asked for account removal after completing the project.",
    status: "Cancelled",
    createdAt: "2025-10-22",
    decisionDate: "2025-10-23",
    managerRemarks: "Cancelled by the sales user before manager action.",
  },
  {
    id: "RQ-1011",
    clientId: 4,
    clientName: "Peak Logistics",
    managerId: 3,
    managerName: "Tara Singh",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Phone Number", oldValue: "+91 90123 45678", newValue: "+91 90123 45679" },
      { field: "Email", oldValue: "contact@peaklogistics.com", newValue: "support@peaklogistics.com" },
    ],
    reason: "Update support contact information.",
    status: "Approved",
    createdAt: "2023-12-01",
    decisionDate: "2023-12-10",
    managerRemarks: "Approved after confirming with client.",
  },
  {
    id: "RQ-1012",
    clientId: 6,
    clientName: "Riverstone Builders",
    managerId: 3,
    managerName: "Tara Singh",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Company Name", oldValue: "Riverstone Construction", newValue: "Riverstone Builders Pvt Ltd" },
    ],
    reason: "Update registered company name.",
    status: "Rejected",
    createdAt: "2024-07-14",
    decisionDate: "2024-07-18",
    managerRemarks: "Rejected because the legal name change was not yet approved.",
  },
  {
    id: "RQ-1013",
    clientId: 1,
    clientName: "Bright Retail",
    managerId: 1,
    managerName: "Mia Ross",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Request removal once the annual contract ends.",
    status: "Approved",
    createdAt: "2025-02-24",
    decisionDate: "2025-03-02",
    managerRemarks: "Approved after contract review.",
  },
  {
    id: "RQ-1014",
    clientId: 2,
    clientName: "Urban Foods",
    managerId: 2,
    managerName: "Rohan Varma",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Client requested removal after migration to a new system.",
    status: "Pending",
    createdAt: "2026-05-06",
    decisionDate: null,
    managerRemarks: null,
  },
  {
    id: "RQ-1015",
    clientId: 3,
    clientName: "Nova Textiles",
    managerId: 1,
    managerName: "Mia Ross",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Email", oldValue: "contact@novatextiles.com", newValue: "hello@novatextiles.com" },
      { field: "Contact Person", oldValue: "Sanjay Patel", newValue: "Sanjay Patel (Lead)" },
    ],
    reason: "Update sales contact details.",
    status: "Pending",
    createdAt: "2026-01-19",
    decisionDate: null,
    managerRemarks: null,
  },
  {
    id: "RQ-1016",
    clientId: 4,
    clientName: "Peak Logistics",
    managerId: 3,
    managerName: "Tara Singh",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Address", oldValue: "38 Freight Lane, Ahmedabad", newValue: "38 Freight Lane, Ahmedabad - Warehouse 7" },
    ],
    reason: "Correct address for logistics office.",
    status: "Approved",
    createdAt: "2025-04-01",
    decisionDate: "2025-04-07",
    managerRemarks: "Approved after verifying the location update.",
  },
  {
    id: "RQ-1017",
    clientId: 5,
    clientName: "Crest Pharma",
    managerId: 2,
    managerName: "Rohan Varma",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Client has merged with another partner and should be removed later.",
    status: "Rejected",
    createdAt: "2024-03-09",
    decisionDate: "2024-03-14",
    managerRemarks: "Rejected due to pending payments.",
  },
  {
    id: "RQ-1018",
    clientId: 6,
    clientName: "Riverstone Builders",
    managerId: 3,
    managerName: "Tara Singh",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Company Name", oldValue: "Riverstone Construction", newValue: "Riverstone Builders Inc." },
      { field: "Phone Number", oldValue: "+91 91222 33445", newValue: "+91 91222 33446" },
    ],
    reason: "Update company name and phone details.",
    status: "Pending",
    createdAt: "2026-02-10",
    decisionDate: null,
    managerRemarks: null,
  },
  {
    id: "RQ-1019",
    clientId: 2,
    clientName: "Urban Foods",
    managerId: 2,
    managerName: "Rohan Varma",
    requestType: "Edit Client",
    requestedChanges: [
      { field: "Company Name", oldValue: "Urban Foods Ltd", newValue: "Urban Foods Pvt Ltd" },
    ],
    reason: "Update company name abbreviation.",
    status: "Approved",
    createdAt: "2024-11-18",
    decisionDate: "2024-11-24",
    managerRemarks: "Approved after client confirmation.",
  },
  {
    id: "RQ-1020",
    clientId: 1,
    clientName: "Bright Retail",
    managerId: 1,
    managerName: "Mia Ross",
    requestType: "Delete Client",
    requestedChanges: [],
    reason: "Remove duplicate client profile once verified.",
    status: "Rejected",
    createdAt: "2025-06-13",
    decisionDate: "2025-06-15",
    managerRemarks: "Rejected until duplicate status is confirmed.",
  },
];
