export const mockRequests = [
  {
    id: 'REQ-1001',
    clientName: 'Bright Retail',
    company: 'Bright Retail Pvt Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'Update corporate contact details after acquisition.',
    requestedChanges: [
      { field: 'Phone Number', oldValue: '+91 98765 32100', newValue: '+91 98765 32199' },
      { field: 'Email', oldValue: 'hello@brightretail.com', newValue: 'contact@brightretail.com' },
      { field: 'GST Number', oldValue: '27AABBCC1234Z1', newValue: '27AABBCC1234Z2' },
    ],
    status: 'Pending',
    createdAt: '2024-06-10',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
  {
    id: 'REQ-1002',
    clientName: 'Urban Foods',
    company: 'Urban Foods Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'Client needs updated billing information.',
    requestedChanges: [
      { field: 'Phone Number', oldValue: '+91 91234 55678', newValue: '+91 91234 55679' },
      { field: 'GST Number', oldValue: '27CCDDFF1234Z1', newValue: '27CCDDFF1234Z2' },
    ],
    status: 'Approved',
    createdAt: '2024-05-21',
    decisionDate: '2024-05-24',
    approvedAt: '2024-05-24',
    approvedBy: 'Ariana Lee',
  },
  {
    id: 'REQ-1003',
    clientName: 'Nova Textiles',
    company: 'Nova Textiles Co',
    salesPerson: 'Rohan Varma',
    branch: 'South',
    requestType: 'Delete Client',
    reason: 'Duplicate client record detected for the same account.',
    requestedChanges: [],
    status: 'Rejected',
    createdAt: '2024-04-09',
    decisionDate: '2024-04-12',
    approvedAt: '2024-04-12',
    approvedBy: 'Priya Menon',
  },
  {
    id: 'REQ-1004',
    clientName: 'Alpha Systems',
    company: 'Alpha Systems Pvt Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Delete Client',
    reason: 'Client account was closed and should be removed.',
    requestedChanges: [],
    status: 'Pending',
    createdAt: '2024-07-02',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
  {
    id: 'REQ-1005',
    clientName: 'Synergy Labs',
    company: 'Synergy Labs Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'Client has moved to a new billing address.',
    requestedChanges: [
      { field: 'Email', oldValue: 'info@synergylabs.com', newValue: 'billing@synergylabs.com' },
      { field: 'GST Number', oldValue: '27EEFFGG1234Z1', newValue: '27EEFFGG1234Z3' },
    ],
    status: 'Pending',
    createdAt: '2024-06-27',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
  {
    id: 'REQ-1006',
    clientName: 'Horizon Retail',
    company: 'Horizon Retail Pvt Ltd',
    salesPerson: 'Tara Singh',
    branch: 'North',
    requestType: 'Edit Client',
    reason: 'Update client tax information for the next quarter.',
    requestedChanges: [
      { field: 'GST Number', oldValue: '27HHIIJJ1234Z1', newValue: '27HHIIJJ1234Z4' },
    ],
    status: 'Approved',
    createdAt: '2024-03-12',
    decisionDate: '2024-03-20',
    approvedAt: '2024-03-20',
    approvedBy: 'Eli Brooks',
  },
  {
    id: 'REQ-1007',
    clientName: 'Metro Auto',
    company: 'Metro Auto Services',
    salesPerson: 'Noah Kim',
    branch: 'West',
    requestType: 'Delete Client',
    reason: 'Client contract terminated and record should be archived.',
    requestedChanges: [],
    status: 'Rejected',
    createdAt: '2023-11-18',
    decisionDate: '2023-11-22',
    approvedAt: '2023-11-22',
    approvedBy: 'Sara Kim',
  },
  {
    id: 'REQ-1008',
    clientName: 'Vertex Design',
    company: 'Vertex Design Studio',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'Client requested update to their primary contact person.',
    requestedChanges: [
      { field: 'Phone Number', oldValue: '+91 99871 22334', newValue: '+91 99871 22335' },
      { field: 'Email', oldValue: 'info@vertexdesign.com', newValue: 'hello@vertexdesign.com' },
    ],
    status: 'Approved',
    createdAt: '2024-05-02',
    decisionDate: '2024-05-05',
    approvedAt: '2024-05-05',
    approvedBy: 'Ariana Lee',
  },
  {
    id: 'REQ-1009',
    clientName: 'Nexa Pharma',
    company: 'Nexa Pharma Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Delete Client',
    reason: 'Duplicate account was created during manual entry.',
    requestedChanges: [],
    status: 'Pending',
    createdAt: '2024-07-06',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
  {
    id: 'REQ-1010',
    clientName: 'Crest Tech',
    company: 'Crest Technologies',
    salesPerson: 'Rohan Varma',
    branch: 'South',
    requestType: 'Edit Client',
    reason: 'Client changed their business email.',
    requestedChanges: [
      { field: 'Email', oldValue: 'support@cresttech.com', newValue: 'contact@cresttech.com' },
    ],
    status: 'Approved',
    createdAt: '2024-01-28',
    decisionDate: '2024-02-02',
    approvedAt: '2024-02-02',
    approvedBy: 'Priya Menon',
  },
  {
    id: 'REQ-1011',
    clientName: 'Eastpoint Logistics',
    company: 'Eastpoint Logistics',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'Update contact and GST information as requested by the client.',
    requestedChanges: [
      { field: 'Phone Number', oldValue: '+91 91111 22334', newValue: '+91 91111 22335' },
      { field: 'GST Number', oldValue: '27KKLLMM1234Z1', newValue: '27KKLLMM1234Z2' },
    ],
    status: 'Approved',
    createdAt: '2023-12-10',
    decisionDate: '2024-01-03',
    approvedAt: '2024-01-03',
    approvedBy: 'Ariana Lee',
  },
  {
    id: 'REQ-1012',
    clientName: 'Apex Interiors',
    company: 'Apex Interiors Pvt Ltd',
    salesPerson: 'Tara Singh',
    branch: 'North',
    requestType: 'Edit Client',
    reason: 'Correct the registered office address.',
    requestedChanges: [
      { field: 'Phone Number', oldValue: '+91 91222 33455', newValue: '+91 91222 33456' },
    ],
    status: 'Pending',
    createdAt: '2024-07-04',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
  {
    id: 'REQ-1013',
    clientName: 'Peak Media',
    company: 'Peak Media Group',
    salesPerson: 'Noah Kim',
    branch: 'West',
    requestType: 'Edit Client',
    reason: 'Client needs new billing contact and GST update.',
    requestedChanges: [
      { field: 'Email', oldValue: 'hello@peakmedia.com', newValue: 'accounts@peakmedia.com' },
      { field: 'GST Number', oldValue: '27NNOOPP1234Z1', newValue: '27NNOOPP1234Z4' },
    ],
    status: 'Rejected',
    createdAt: '2024-02-18',
    decisionDate: '2024-02-24',
    approvedAt: '2024-02-24',
    approvedBy: 'Sara Kim',
  },
  {
    id: 'REQ-1014',
    clientName: 'Vista Energy',
    company: 'Vista Energy Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Delete Client',
    reason: 'Client cancelled the contract and should be removed.',
    requestedChanges: [],
    status: 'Approved',
    createdAt: '2024-03-05',
    decisionDate: '2024-03-07',
    approvedAt: '2024-03-07',
    approvedBy: 'Ariana Lee',
  },
  {
    id: 'REQ-1015',
    clientName: 'Core Manufacturing',
    company: 'Core Manufacturing Co',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'The client updated their GST and contact details.',
    requestedChanges: [
      { field: 'Phone Number', oldValue: '+91 93456 77889', newValue: '+91 93456 77890' },
      { field: 'GST Number', oldValue: '27QQRRS1234Z1', newValue: '27QQRRS1234Z2' },
    ],
    status: 'Pending',
    createdAt: '2024-06-14',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
  {
    id: 'REQ-1016',
    clientName: 'Nova Textiles',
    company: 'Nova Textiles Co',
    salesPerson: 'Rohan Varma',
    branch: 'South',
    requestType: 'Edit Client',
    reason: 'Corrected gst details after billing audit.',
    requestedChanges: [
      { field: 'GST Number', oldValue: '27SSUUV1234Z1', newValue: '27SSUUV1234Z3' },
    ],
    status: 'Approved',
    createdAt: '2023-12-21',
    decisionDate: '2024-01-05',
    approvedAt: '2024-01-05',
    approvedBy: 'Priya Menon',
  },
  {
    id: 'REQ-1017',
    clientName: 'Zenith Health',
    company: 'Zenith Health Care',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Delete Client',
    reason: 'Client data was entered twice and needs clean up.',
    requestedChanges: [],
    status: 'Pending',
    createdAt: '2024-07-08',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
  {
    id: 'REQ-1018',
    clientName: 'Summit Co',
    company: 'Summit Co.',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'New contact details were requested by client.',
    requestedChanges: [
      { field: 'Phone Number', oldValue: '+91 91234 56789', newValue: '+91 91234 56790' },
      { field: 'Email', oldValue: 'hello@summitco.com', newValue: 'contact@summitco.com' },
    ],
    status: 'Rejected',
    createdAt: '2024-02-11',
    decisionDate: '2024-02-18',
    approvedAt: '2024-02-18',
    approvedBy: 'Ariana Lee',
  },
  {
    id: 'REQ-1019',
    clientName: 'Blue Retail',
    company: 'Blue Retail Pvt Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Delete Client',
    reason: 'Company has been merged into another account.',
    requestedChanges: [],
    status: 'Approved',
    createdAt: '2024-04-05',
    decisionDate: '2024-04-08',
    approvedAt: '2024-04-08',
    approvedBy: 'Ariana Lee',
  },
  {
    id: 'REQ-1020',
    clientName: 'Evergreen Foods',
    company: 'Evergreen Foods Pvt Ltd',
    salesPerson: 'Mia Ross',
    branch: 'East',
    requestType: 'Edit Client',
    reason: 'A new GST number was issued after registration.',
    requestedChanges: [
      { field: 'GST Number', oldValue: '27TTUUV1234Z1', newValue: '27TTUUV1234Z5' },
    ],
    status: 'Pending',
    createdAt: '2024-07-09',
    decisionDate: null,
    approvedAt: null,
    approvedBy: null,
  },
];
