export const mockEligibleSchemes = [
  {
    id: 1,
    schemeName: "PMEGP",
    description: "Prime Minister Employment Generation Programme for new entrepreneurs.",
    eligible: true,
    visibleToClient: true,
    lastUpdated: "2026-08-01",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 2,
    schemeName: "Mudra Loan",
    description: "Collateral-free financing support for micro and small businesses.",
    eligible: true,
    visibleToClient: true,
    lastUpdated: "2026-07-28",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 3,
    schemeName: "Stand-Up India",
    description: "Support for SC, ST, and women entrepreneurs to start new ventures.",
    eligible: true,
    visibleToClient: false,
    lastUpdated: "2026-07-24",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 4,
    schemeName: "Startup India",
    description: "Recognition and startup ecosystem support for innovative ventures.",
    eligible: true,
    visibleToClient: false,
    lastUpdated: "2026-07-20",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 5,
    schemeName: "MSME Subsidy",
    description: "Capital and operational support for eligible MSME clients.",
    eligible: true,
    visibleToClient: true,
    lastUpdated: "2026-07-18",
    updatedBy: "Eligibility Engine",
  },
  {
    id: 6,
    schemeName: "CGTMSE",
    description: "Credit guarantee support for loans extended to small businesses.",
    eligible: true,
    visibleToClient: false,
    lastUpdated: "2026-07-15",
    updatedBy: "Eligibility Engine",
  },
];
