export const mockClients = [
  {
    id: 1,
    name: "Bright Retail",
    company: "Bright Retail Pvt Ltd",
    contactPerson: "Anil Kumar",
    phone: "+91 98765 32100",
    email: "hello@brightretail.com",
    gstNumber: "27ABCDE1234F1Z5",
    address: "101 MG Road, Mumbai",
    managerId: 1,
    managerName: "Mia Ross",
  },
  {
    id: 2,
    name: "Urban Foods",
    company: "Urban Foods Ltd",
    contactPerson: "Riya Sharma",
    phone: "+91 91234 55678",
    email: "sales@urbanfoods.com",
    gstNumber: "27PQRSX6789K1Z1",
    address: "22 Brigade Road, Bengaluru",
    managerId: 2,
    managerName: "Rohan Varma",
  },
  {
    id: 3,
    name: "Nova Textiles",
    company: "Nova Textiles Co",
    contactPerson: "Sanjay Patel",
    phone: "+91 99876 44556",
    email: "contact@novatextiles.com",
    gstNumber: "27LMNOP4321D1Z3",
    address: "17 Industrial Park, Surat",
    managerId: 1,
    managerName: "Mia Ross",
  },
  {
    id: 4,
    name: "Peak Logistics",
    company: "Peak Logistics Pvt Ltd",
    contactPerson: "Rakesh Mehra",
    phone: "+91 90123 45678",
    email: "contact@peaklogistics.com",
    gstNumber: "27RSTUV9876P1Z2",
    address: "38 Freight Lane, Ahmedabad",
    managerId: 3,
    managerName: "Tara Singh",
  },
  {
    id: 5,
    name: "Crest Pharma",
    company: "Crest Pharmaceuticals",
    contactPerson: "Deepa Joshi",
    phone: "+91 98700 11223",
    email: "support@crestpharma.com",
    gstNumber: "27CREST1234H1Z7",
    address: "45 Pharma Avenue, Hyderabad",
    managerId: 2,
    managerName: "Rohan Varma",
  },
  {
    id: 6,
    name: "Riverstone Builders",
    company: "Riverstone Construction",
    contactPerson: "Amit Sinha",
    phone: "+91 91222 33445",
    email: "office@riverstone.in",
    gstNumber: "27RIVST5678M1Z3",
    address: "72 Builder Street, Pune",
    managerId: 3,
    managerName: "Tara Singh",
  },
];
