export const initialBranches = [
  {
    id: "BR-01",
    name: "West Zone (Mumbai)",
    city: "Mumbai, Maharashtra",
    manager: "Ariana Lee",
    adminLead: "Vikramaditya Roy",
    headcount: 18,
    activeClients: 42,
    target: "₹4,500,000",
    achieved: "₹4,120,000",
    status: "Active",
  },
  {
    id: "BR-02",
    name: "North Zone (Delhi)",
    city: "New Delhi, NCR",
    manager: "Devendra Patil",
    adminLead: "Ramesh Saxena",
    headcount: 14,
    activeClients: 35,
    target: "₹3,800,000",
    achieved: "₹3,450,000",
    status: "Active",
  },
  {
    id: "BR-03",
    name: "South Zone (Bengaluru)",
    city: "Bengaluru, Karnataka",
    manager: "Sunita Nambiar",
    adminLead: "Kavita Reddy",
    headcount: 16,
    activeClients: 39,
    target: "₹4,200,000",
    achieved: "₹3,980,000",
    status: "Active",
  },
  {
    id: "BR-04",
    name: "East Zone (Kolkata)",
    city: "Kolkata, West Bengal",
    manager: "Siddharth Ghosh",
    adminLead: "Arup Banerjee",
    headcount: 10,
    activeClients: 22,
    target: "₹2,500,000",
    achieved: "₹2,180,000",
    status: "Active",
  },
  {
    id: "BR-05",
    name: "Central Hub (Nagpur)",
    city: "Nagpur, Maharashtra",
    manager: "Anand Deshmukh",
    adminLead: "Pooja Joshi",
    headcount: 8,
    activeClients: 15,
    target: "₹1,800,000",
    achieved: "₹1,620,000",
    status: "Active",
  },
];

export const ACTIVITY_STAGES = [
  {
    step: 1,
    name: "Submission",
    percent: 20,
    badgeColor: "#10b981",
    description: "Application & initial token registration submitted",
  },
  {
    step: 2,
    name: "Doc Audit",
    percent: 40,
    badgeColor: "#10b981",
    description: "PAN, Aadhar, GSTIN & KYC documents verified",
  },
  {
    step: 3,
    name: "Manager Review",
    percent: 60,
    badgeColor: "#10b981",
    description: "Branch manager & commercial underwriting approval cleared",
  },
  {
    step: 4,
    name: "Agreement",
    percent: 80,
    badgeColor: "#f59e0b",
    description: "Legal agreement execution, scheme bond & terms issued",
  },
  {
    step: 5,
    name: "Final Approval",
    percent: 100,
    badgeColor: "#10b981",
    description: "Final administrative sign-off, live policy disbursement",
  },
];

export const APPLICATION_STAGES = [
  { name: "Submission", progress: 20, step: 1, badgeColor: "#4e7cff", description: "Application intake submitted by sales" },
  { name: "Doc Audit", progress: 40, step: 2, badgeColor: "#9a74e9", description: "Admin verifying PAN, Aadhar, GST & KYC documents" },
  { name: "Manager Review", progress: 60, step: 3, badgeColor: "#f2aa38", description: "Branch manager risk evaluation and review" },
  { name: "Agreement", progress: 80, step: 4, badgeColor: "#26a69a", description: "Scheme agreement & sanction letter prepared" },
  { name: "Final Approval", progress: 100, step: 5, badgeColor: "#10b981", description: "Final approval & scheme active/disbursed" },
];

export const initialBranchClients = [
  {
    id: 1,
    appId: "APP-WZ-2026-001",
    name: "Bright Retail",
    contactPerson: "Anil Kumar",
    company: "Bright Retail Pvt Ltd",
    email: "hello@brightretail.com",
    phone: "+91 98765 32100",
    address: "101 MG Road, Fort, Mumbai",
    branch: "West Zone (Mumbai)",
    scheme: "Enterprise Growth Scheme",
    amount: 50000,
    gstAmount: 9000,
    totalPayment: 59000,
    paymentMode: "Online",
    paymentStatus: "Paid",
    applicationStatus: "Final Approval",
    progress: 100,
    completedSteps: ["Submission", "Doc Audit", "Manager Review", "Agreement", "Final Approval"],
    assignedSalesPerson: "Mia Ross",
    submissionDate: "2026-08-02",
    lastUpdated: "2026-08-14 16:45",
    adminNotes: "All compliance documents verified. Premium policy issued and activated.",
    documents: [
      { name: "PAN Card", status: "Verified", number: "ABCDE1234F" },
      { name: "Aadhar Card", status: "Verified", number: "1234 5678 9012" },
      { name: "GSTIN Certificate", status: "Verified", number: "27ABCDE1234F1Z5" },
      { name: "KYC Dossier", status: "Verified", number: "KYC-OK-8819" },
    ],
    history: [
      { date: "2026-08-02", status: "Submission", updatedBy: "Mia Ross (Sales)", notes: "Application submitted with initial payment." },
      { date: "2026-08-05", status: "Doc Audit", updatedBy: "Branch Admin", notes: "PAN and GSTIN verified against government portal." },
      { date: "2026-08-09", status: "Manager Review", updatedBy: "Branch Admin", notes: "Risk profile assessed. Clean record." },
      { date: "2026-08-12", status: "Agreement", updatedBy: "Branch Admin", notes: "Final agreement drafted and signed by client." },
      { date: "2026-08-14", status: "Final Approval", updatedBy: "Branch Admin", notes: "Scheme active and welcome kit dispatched." },
    ],
  },
  {
    id: 2,
    appId: "APP-WZ-2026-002",
    name: "Urban Foods",
    contactPerson: "Riya Sharma",
    company: "Urban Foods Ltd",
    email: "sales@urbanfoods.com",
    phone: "+91 91234 55678",
    address: "22 Brigade Road, Indiranagar, Bengaluru",
    branch: "West Zone (Mumbai)",
    scheme: "Retail Scale-Up Program",
    amount: 45000,
    gstAmount: 8100,
    totalPayment: 53100,
    paymentMode: "Online",
    paymentStatus: "Partial",
    applicationStatus: "Doc Audit",
    progress: 40,
    completedSteps: ["Submission", "Doc Audit"],
    assignedSalesPerson: "Mia Ross",
    submissionDate: "2026-08-06",
    lastUpdated: "2026-08-15 10:20",
    adminNotes: "Aadhar copy clear. Waiting on updated GST registration certificate with Mumbai branch address.",
    documents: [
      { name: "PAN Card", status: "Verified", number: "PQRSX6789K" },
      { name: "Aadhar Card", status: "Verified", number: "2345 6789 0123" },
      { name: "GSTIN Certificate", status: "Pending Review", number: "27PQRSX6789K1Z1" },
      { name: "KYC Dossier", status: "Pending Review", number: "KYC-PEND-4402" },
    ],
    history: [
      { date: "2026-08-06", status: "Submission", updatedBy: "Mia Ross (Sales)", notes: "Client registered with partial advance." },
      { date: "2026-08-10", status: "Doc Audit", updatedBy: "Branch Admin", notes: "PAN verified. Requested re-upload of GST certificate." },
    ],
  },
  {
    id: 3,
    appId: "APP-NZ-2026-003",
    name: "Apex Logistics",
    contactPerson: "Rajiv Khurana",
    company: "Apex Fleet Logistics Pvt Ltd",
    email: "rajiv@apexlogistics.in",
    phone: "+91 98111 22334",
    address: "B-44 Connaught Place, New Delhi",
    branch: "North Zone (Delhi)",
    scheme: "Fleet Modernization Grant",
    amount: 110000,
    gstAmount: 19800,
    totalPayment: 129800,
    paymentMode: "Online",
    paymentStatus: "Paid",
    applicationStatus: "Manager Review",
    progress: 60,
    completedSteps: ["Submission", "Doc Audit", "Manager Review"],
    assignedSalesPerson: "Rohan Varma",
    submissionDate: "2026-08-08",
    lastUpdated: "2026-08-15 09:15",
    adminNotes: "Fleet inspection report submitted. Manager review valuation in progress.",
    documents: [
      { name: "PAN Card", status: "Verified", number: "LMNOP9988D" },
      { name: "Aadhar Card", status: "Verified", number: "3456 7890 9988" },
      { name: "GSTIN Certificate", status: "Verified", number: "07LMNOP9988D1Z9" },
      { name: "Vehicle RC & Fleet Deck", status: "Verified", number: "FL-220-DL" },
    ],
    history: [
      { date: "2026-08-08", status: "Submission", updatedBy: "Rohan Varma (Sales)", notes: "Fleet application submitted." },
      { date: "2026-08-11", status: "Doc Audit", updatedBy: "Branch Admin", notes: "All vehicle RC documents checked." },
      { date: "2026-08-14", status: "Manager Review", updatedBy: "Branch Admin", notes: "Commercial risk evaluation under manager review." },
    ],
  },
  {
    id: 4,
    appId: "APP-WZ-2026-004",
    name: "Nova Textiles",
    contactPerson: "Sanjay Patel",
    company: "Nova Textiles Co",
    email: "contact@novatextiles.com",
    phone: "+91 99876 44556",
    address: "17 Industrial Park, Ring Road, Surat",
    branch: "West Zone (Mumbai)",
    scheme: "Textile Machinery Subsidy",
    amount: 75000,
    gstAmount: 0,
    totalPayment: 75000,
    paymentMode: "Offline",
    paymentStatus: "Paid",
    applicationStatus: "Agreement",
    progress: 80,
    completedSteps: ["Submission", "Doc Audit", "Manager Review", "Agreement"],
    assignedSalesPerson: "Mia Ross",
    submissionDate: "2026-08-01",
    lastUpdated: "2026-08-13 14:10",
    adminNotes: "Subsidy agreement executed. Final signature on subsidy disbursement schedule pending.",
    documents: [
      { name: "PAN Card", status: "Verified", number: "LMNOP4321D" },
      { name: "Aadhar Card", status: "Verified", number: "3456 7890 1234" },
      { name: "GSTIN Certificate", status: "Verified", number: "24LMNOP4321D1Z3" },
      { name: "Machinery Invoice", status: "Verified", number: "INV-MACH-99" },
    ],
    history: [
      { date: "2026-08-01", status: "Submission", updatedBy: "Mia Ross (Sales)", notes: "Direct wire payment received." },
      { date: "2026-08-04", status: "Doc Audit", updatedBy: "Branch Admin", notes: "All factory papers verified." },
      { date: "2026-08-09", status: "Manager Review", updatedBy: "Branch Admin", notes: "Machinery valuation cleared." },
      { date: "2026-08-13", status: "Agreement", updatedBy: "Branch Admin", notes: "Disbursement agreement signed." },
    ],
  },
  {
    id: 5,
    appId: "APP-WZ-2026-005",
    name: "Peak Logistics",
    contactPerson: "Rakesh Mehra",
    company: "Peak Logistics Pvt Ltd",
    email: "contact@peaklogistics.com",
    phone: "+91 90123 45678",
    address: "38 Freight Lane, GIDC, Ahmedabad",
    branch: "West Zone (Mumbai)",
    scheme: "Fleet Modernization Grant",
    amount: 120000,
    gstAmount: 21600,
    totalPayment: 141600,
    paymentMode: "Online",
    paymentStatus: "Partial",
    applicationStatus: "Submission",
    progress: 20,
    completedSteps: ["Submission"],
    assignedSalesPerson: "Mia Ross",
    submissionDate: "2026-08-09",
    lastUpdated: "2026-08-15 08:30",
    adminNotes: "Aadhar card upload failed checksum verification. Salesperson notified to request fresh copy.",
    documents: [
      { name: "PAN Card", status: "Verified", number: "RSTUV9876P" },
      { name: "Aadhar Card", status: "Rejected", number: "4567 8901 2345" },
      { name: "GSTIN Certificate", status: "Verified", number: "24RSTUV9876P1Z2" },
    ],
    history: [
      { date: "2026-08-09", status: "Submission", updatedBy: "Mia Ross (Sales)", notes: "Application received." },
      { date: "2026-08-12", status: "Submission", updatedBy: "Branch Admin", notes: "Aadhar document unreadable/rejected. Placed on hold for re-upload." },
    ],
  },
  {
    id: 6,
    appId: "APP-SZ-2026-006",
    name: "Zenith MedTech",
    contactPerson: "Dr. Arvind Swamy",
    company: "Zenith Medical Solutions",
    email: "arvind@zenithmed.in",
    phone: "+91 97400 11223",
    address: "7th Main Road, Koramangala, Bengaluru",
    branch: "South Zone (Bengaluru)",
    scheme: "Healthcare Infrastructure Grant",
    amount: 180000,
    gstAmount: 32400,
    totalPayment: 212400,
    paymentMode: "Online",
    paymentStatus: "Paid",
    applicationStatus: "Agreement",
    progress: 80,
    completedSteps: ["Submission", "Doc Audit", "Manager Review", "Agreement"],
    assignedSalesPerson: "Sunita Nambiar",
    submissionDate: "2026-08-03",
    lastUpdated: "2026-08-14 12:00",
    adminNotes: "Medical equipment credentials cleared by Bengaluru healthcare desk. Agreement executed.",
    documents: [
      { name: "PAN Card", status: "Verified", number: "MEDIC1234M" },
      { name: "Aadhar Card", status: "Verified", number: "5678 9012 3456" },
      { name: "GSTIN Certificate", status: "Verified", number: "29MEDIC1234M1Z8" },
      { name: "NABH / Medical License", status: "Verified", number: "NABH-BLR-401" },
    ],
    history: [
      { date: "2026-08-03", status: "Submission", updatedBy: "Sunita Nambiar", notes: "Medical grant proposal registered." },
      { date: "2026-08-07", status: "Doc Audit", updatedBy: "South Admin", notes: "Clinical license validated." },
      { date: "2026-08-11", status: "Manager Review", updatedBy: "South Admin", notes: "Approved grant structure." },
      { date: "2026-08-14", status: "Agreement", updatedBy: "South Admin", notes: "Grant agreement confirmed." },
    ],
  },
  {
    id: 7,
    appId: "APP-WZ-2026-007",
    name: "Kalyan Jewels & Crafts",
    contactPerson: "Deepak Soni",
    company: "Kalyan Crafts Enterprise",
    email: "deepak@kalyancrafts.com",
    phone: "+91 98222 33445",
    address: "Zaveri Bazaar, Kalbadevi, Mumbai",
    branch: "West Zone (Mumbai)",
    scheme: "Artisan & MSME Capital Scheme",
    amount: 35000,
    gstAmount: 6300,
    totalPayment: 41300,
    paymentMode: "Online",
    paymentStatus: "Paid",
    applicationStatus: "Submission",
    progress: 20,
    completedSteps: ["Submission"],
    assignedSalesPerson: "Mia Ross",
    submissionDate: "2026-08-15",
    lastUpdated: "2026-08-15 11:45",
    adminNotes: "Fresh application submitted today. Initial queue intake.",
    documents: [
      { name: "PAN Card", status: "Uploaded", number: "SONIX5566K" },
      { name: "Aadhar Card", status: "Uploaded", number: "6789 0123 4567" },
      { name: "MSME Certificate", status: "Uploaded", number: "UDYAM-MH-01-002" },
    ],
    history: [
      { date: "2026-08-15", status: "Submission", updatedBy: "Mia Ross (Sales)", notes: "Application filed with initial token payment." },
    ],
  },
];

export const initialBranchTeam = [
  {
    id: 1,
    name: "Ariana Lee",
    role: "Branch Manager",
    branch: "West Zone (Mumbai)",
    email: "ariana@agni.com",
    phone: "+91 98202 22334",
    assignedClients: 18,
    status: "Active",
  },
  {
    id: 2,
    name: "Vikramaditya Roy",
    role: "Branch Admin Lead",
    branch: "West Zone (Mumbai)",
    email: "vikram.admin@agni.com",
    phone: "+91 98201 11223",
    assignedClients: 42,
    status: "Active",
  },
  {
    id: 3,
    name: "Mia Ross",
    role: "Senior Sales Person",
    branch: "West Zone (Mumbai)",
    email: "mia@agni.com",
    phone: "+91 98205 55667",
    assignedClients: 14,
    status: "Active",
  },
  {
    id: 4,
    name: "Alex Vance",
    role: "Sales Executive",
    branch: "West Zone (Mumbai)",
    email: "alex@agni.com",
    phone: "+91 98205 55668",
    assignedClients: 10,
    status: "Active",
  },
];

export const stageBadgeColors = {
  Submission: "#4e7cff",
  "Doc Audit": "#9a74e9",
  "Manager Review": "#f2aa38",
  Agreement: "#26a69a",
  "Final Approval": "#10b981",
  "Active & Disbursed": "#10b981",
  "Document Verification": "#9a74e9",
  Underwriting: "#f2aa38",
  Approved: "#26a69a",
  Submitted: "#4e7cff",
  "On Hold": "#ff9800",
  Rejected: "#ff5757",
};

export const formatCurrency = (val) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(val || 0);

